services:
  db:
    image: mysql:8.0
    container_name: artes_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: artes
      MYSQL_USER: artes
      MYSQL_PASSWORD: artes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: artes_pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"

  php:
    build: ./php
    container_name: artes_php
    restart: unless-stopped
    volumes:
      - ./site:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: artes_nginx
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  waha:
    image: devlikeapro/waha:latest
    container_name: artes_waha
    restart: unless-stopped
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    environment:
      - WAHA_API_KEY=dec771db080c466da9a621b11e457358
      - WAHA_DASHBOARD_USERNAME=admin
      - WAHA_DASHBOARD_PASSWORD=849c3b3edc224ff8ae3745e9b008852d
      - WHATSAPP_SWAGGER_USERNAME=admin
      - WHATSAPP_SWAGGER_PASSWORD=849c3b3edc224ff8ae3745e9b008852d
      - WHATSAPP_HOOK_URL=http://nginx/api/whatsapp-webhook.php
      - WHATSAPP_HOOK_EVENTS=message
    volumes:
      - waha_data:/app/sessions

volumes:
  db_data:
  waha_data:
